services:
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.0
    restart: always
    networks:
      - evolution-net
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DATABASE_PROVIDER: ${DATABASE_PROVIDER}
      DATABASE_URL: ${DATABASE_URL}

      CACHE_REDIS: "true"
      CACHE_REDIS_HOST: redis
      CACHE_REDIS_PORT: 6379

      SERVER_PORT: 8080
    depends_on:
      - postgres
      - redis
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_uploads:/evolution/uploads
      - evolution_config:/evolution/config

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    environment:
      PGADMIN_DEFAULT_EMAIL: EMAIL
      PGADMIN_DEFAULT_PASSWORD: PASSWORD
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "4000:80"

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - "6379:6379"

networks:
  evolution-net:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  evolution_instances:
  evolution_uploads:
  evolution_config:
